name: guitar_theory_app
description: A new Flutter project for Guitar & Theory Explorer.
publish_to: 'none'
version: 1.1.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.0.0
  
  # UI & Assets
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  
  # Routing
  go_router: ^17.0.1
  url_strategy: ^0.3.0
  url_launcher: ^6.3.0

  # Logic & Data
  collection: ^1.17.0
  tonic: ^0.2.5
  js: ^0.7.1
  
  # Audio
  flutter_soloud: ^3.4.6
  sound_stream: ^0.3.0
  
  # Desktop
  window_manager: ^0.3.9
  
  # AI
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.6.22
  shared_preferences: ^2.2.0
  path_provider: ^2.1.2
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1
  dart_openai: ^6.1.1

  http: ^1.2.0        # API 통신
  web_socket_channel: ^3.0.0
  audioplayers: ^6.0.0 # 오디오 재생

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.ico"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/sounds/
    - assets/images/
    - README.md
